### ISSUE TITLE
Provide instructions how to prepare necessary data input

### ISSUE THREAD

**Issue by TilmannF** [xlejx-rodsxn/sar_migration#2]
In your [paper](https://www.nature.com/articles/s41598-023-38119-4) you've wrote
> Though most data sources are publicly available—with the exception of the Sabre data on air traffic, we are unable to upload our data set to a repository due to data-usage requirements and proprietary restrictions.

First of all this is not true in case of most of the Eurostat data [as they clearly state](https://ec.europa.eu/eurostat/about-us/policies/copyright):
> Eurostat has a policy of encouraging free re-use of its data, both for non-commercial and commercial purposes. All statistical data, metadata, content of web pages or other dissemination tools, official publications and other documents published on its website, with the exceptions listed below, can be reused without any payment or written licence provided that:
> - the source is indicated as Eurostat;
> - when re-use involves modifications to the data or text, this must be stated clearly to the end user of the information.

It is also not true in case of [Missing Migrants Project](https://missingmigrants.iom.int/downloads):
> The downloads above are licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/). This means that Missing Migrants Project data are free to share and adapt, as long as the appropriate attribution is given. This includes stating that the source is 'IOM's Missing Migrants Project', and indicating if changes were made to the data. Ideally, a link to this website should also be included.

And while there are certain data providers which do not have such open license models, it is considered best practice to provide a detailed guide on where to obtain & prepare the data necessary to run the software.

**Comment by xlejx-rodsxn** [comment]
The details of the data are given in the paper (supplementary materials table s1) and in the code that shows exactly how to do this for each of the data source. we didnt write a tutorial for how to do the analysis unfortunately, but if people are interested in this, Id be happy to collaborate. You will not be able to replicate the analysis unless you have access to the Sabre data or EM-DAT for environmental factors, for example, nor the ACLED data, equally so for UNITED data, etc., for which no CC exist or permission is needed (pending approval). We are not using  ony Eurostat  and IOM data. Please read carefully our paper before opening issues that aren't issues. The statement in the paper refers to the full data base which we cannot distribute here under any circumstances. Like we say it in the paper, if you are interested in obtaining the data for replication purposes or further analysis at Zalando, please make a formal request to the email provided in the paper.

**Comment by TilmannF** [comment]
I am acting as individual open source software enthusiast with a lot of experience in software engineering - not as part of an organization. Which is hopefully obvious to everyone since I've created this issue during the weekend & contributed via a profile for individuals instead of an organization profile. I have absolutely zero knowledge about the intention of study replication by any organization & am acting 100% on my own.

If you're not interested in improving the code on this platform (which is perfectly fine), you can [disable issues](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/disabling-issues) & [archive the repo](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) to indicate the dormant status to everyone.

As a final note I would like to kindly point out that this paper was in part made possible by the endless contributions of the open source software communities behind R. While you have no obligation to adhere to common standards in this community even when you use these services, many enthusiast like me would consider it friendly & support you if you try.

Have a great weekend 🙂

**Comment by xlejx-rodsxn** [comment]
Not clear at all what you do or dont. In your profile it says Zalando and is nice you are interested in the study. Start by reading the paper fully first. Many companies do research or have research departments, so maybe Zalando is interested. I share the code with everyone in this platform and mostly with reviewers and people within the academic community, and so far you have not commented on the code to recreate the findings, improve the model or criticize the paper, in fact youodidnt even read the paper. Pls do so. Otherwise I might have to flash your "contribution" to this "community" as trolling of a white dude against a woman of color, something this community is rather well known for. Have a nice weekend.
