### ISSUE TITLE
Why are search-and-rescue operations not a 'pull-factor'?

### ISSUE THREAD

**Issue by chrisdane** [xlejx-rodsxn/sar_migration#3]
Hi

In [Rodríguez Sánchez et al. 2023](https://www.nature.com/articles/s41598-023-38119-4) you define the number of attempted migrant crossings`Y_t` at time `t` as the sum of arrivals to Italy and Malta `A_t`, pushbacks to Libya and Tunisia `P_t` and recorded deaths while on transit `D_t`: `Y_t = A_t + P_t + D_t`. Then you model `Y_t` as `\hat{Y}_t = f(\bold{X_t})` with `f()` being a Bayesian structural time-series model (BSTS) and `\bold{X_t}` a set of temporally resolved covariates. The utilized data sets for `Y_t` and `\bold{X_t}` are listed in Table S1:
1. number of asylum applications to EU
2. number of attempted crossings
3. number of arrivals in Italy and Malta
4. number of flight passengers from African and MENA region countries to Europe
5. number of persons being 'pushed back'
6. number of death/missing migrants (several data sets)
7. African and MENA region currencies’ exchange rates with Euro
8. job search indicators in Africa (google index)
9. number of conflicts in Africa
10. intensity of Syrian conflict (google index)
11. commodity prices
12. number of environmental disasters
13. temperature, precipitation amount and number of storms in Italy and Malta
14. unemployment rates in the European Union and 'EA' (what means EA?)
15. EU operations (1 if active, 0 if not)
16. NGO search-and-rescure opertations (1 if active, 0 if not)

Fig. 2 shows `Y_t` (i.e. the assumed truth) as solid black line and the model result `\hat{Y}_t` as dashed blue line. They are very similar during the respective intervention periods (red background), especially during the presence of state- (Fig. 2A) or private-led (Fig. 2B) search-and-rescue operations. From this you conclude that
> This empirical evidence directly contradicts the 'pull factor' claim given that the difference between the prediction and observed series is far from statistically significant. In other words, based on our selection of other 'push-and-pull factors', a similar number of crossing attempts was to be expected during the period where private-led search-and-rescue was the most active.

, i.e. that search-and-rescue operations are not a 'pull-factor'.

If I misunderstood things until here I would be very thankful if you could find the time to correct my understanding.

If I got the main idea more or less right until this point, I have some questions and I would be very thankful if you could find the time for a reply.

1. It is not clear to me which rows of Table S1 go into `Y_t` and which into `\bold{X_t}`. Could you clarify?
2. I do not understand how you draw your conclusion that search-and-rescue operations are not a 'pull-factor'. Can you please explain for the general public? (I am no expert)

I wonder if these two questions are closely related.

Thanks a lot for your important work and kind regards,
Chris

**Comment by chrisdane** [comment]
lol?

**Comment by xlejx-rodsxn** [comment]
This isn't an issue with the code and no place to reply to questions related to content. The construction of variables is explained in detail in the text. Write an email if you need clarifications. Not an issue
